name: Generate Mobile Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build Android APK and AAB (Testing flavor)
        run: |
          cd android
          ./gradlew assembleQaRelease bundleQaRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/qa/release/**/*.apk

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-aab
          path: android/app/build/outputs/bundle/qaRelease/**/*.aab
  deploy:
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEYSTORE_PATH: upload-keystore.jks
      PLAY_STORE_JSON: ${{ secrets.PLAY_STORE_JSON }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Create keystore directory and decode keystore
        run: |
          mkdir -p android/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/keystore/release-key.jks
        
      - name: Decode Play Store JSON
        run: echo "${{ secrets.PLAY_STORE_JSON }}" > /tmp/playstore.json

      - name: Set up Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler and Fastlane
        run: |
          gem install bundler
          bundle install || gem install fastlane

      # - name: Build QA Release AAB
      #   run: ./gradlew bundleQaRelease

      - name: Deploy to Internal Testing
        run: |
          AAB_FILE=$(find android/app/build/outputs/bundle/qaRelease -name "*.aab" | head -n 1)
          fastlane android deploy_test aab_path:"$AAB_FILE" json_key:"/tmp/playstore.json"

  cleanup:
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GIT_TOKEN }}" | gh auth login --with-token

      - name: Delete Old Artifacts
        run: |
          for ID in $(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.expired == false) | .id'); do
            gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$ID
            echo "Deleted artifact ID: $ID"
          done || true
